#!/bin/bash
set -eu

usage() {
cat <<- EOF
Usage: gkloud [command]

  CLI proof of concept for proposed gcloud unlock command

  Commands:
    unlock       print Google Cloud marketing easter eggs
    help         print help for command

EOF
}

info() {
	echo "INFO: " "$@"
}

error() {
	echo "ERROR: " "$@" >&2
	exit 1
}

if [[ "$#" == "0" ]] || [[ "$1" != "unlock" ]]; then
	usage
	exit 1
fi

# terminal info
is_tty=$(tty -s && echo "true" || echo "false")
read -r height width < <(stty size)


echo "tty: $is_tty, height: $height, width: $width"


